/*
 * LocationIQ LocationIQ provides flexible enterprise-grade location based solutions. We work with developers,
 * startups and enterprises worldwide serving billions of requests everyday. This page provides an overview of
 * the technical aspects of our API and will help you get started.
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech Do not edit the class manually.
 */

package com.locationiq.client.model;

import org.junit.Test;

/**
 * Model tests for Namedetails
 */
public class NamedetailsTest {
    private final Namedetails model = new Namedetails();

    /**
     * Model tests for Namedetails
     */
    @Test
    public void testNamedetails() {
        // TODO: test Namedetails
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
